# netlify.toml
[build]
command = "NODE_OPTIONS='--max_old_space_size=3072' npm run build"
publish = ".next" # Netlify plugin suele manejar esto; mantenlo si ya lo tenías distinto

[build.environment]
# Evita sourcemaps pesados del lado del cliente
NEXT_DISABLE_SOURCEMAPS = "1"
NEXT_TELEMETRY_DISABLED = "1"

# Si continúas con OOM, sube a 4096
# NODE_OPTIONS = "--max_old_space_size=4096"
